services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_db
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=KMY
      - APP_USER_PASSWORD=oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: ../.devcontainer/backend/Dockerfile
    container_name: spring_backend
    command: sleep infinity
    volumes:
      - ..:/workspaces/da:cached
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db

  frontend:
    build:
      context: ../frontend
      dockerfile: ../.devcontainer/frontend/Dockerfile
    container_name: react_frontend
    command: sleep infinity
    volumes:
      - ..:/workspaces/da:cached
    ports:
      - "3000:3000"

volumes:
  oracle_data:
  maven_cache: