-- ============================================================
-- FILE   : V1_Initial_Setup.sql
-- PROJECT: Hệ Thống Quản Lý Dịch Vụ Thị Lực & Thiết Bị Y Tế
-- STACK  : Oracle SQL 21c + Spring Boot + React.js
-- ============================================================
-- CHANGELOG (Final):
--   [+] CHI_TIET_KY_THUAT   — chuyên môn/chứng chỉ Bác sĩ & KTV
--   [+] XU_LY_KINH          — luồng cắt kính theo đơn
--   [+] DANH_GIA            — rating + feedback sau khám
--   [+] GOI_KHAM            — gói dịch vụ booking
--   [+] KHUYEN_MAI / KH_KHUYEN_MAI — loyalty & voucher
--   [+] GIAO_DICH_NCC       — giao dịch nhà cung cấp
--   [+] CV06 Lễ tân         — seed chức vụ + nhóm
--   [FIX] Xóa PRAGMA AUTONOMOUS_TRANSACTION khỏi trigger validate
--   [FIX] DICH_VU_KHAM tạo trước CT_HOA_DON_DV (FK dependency)
--   [FIX] SAN_PHAM thêm TON_KHO_TOI_THIEU, DON_VI_TINH_KHO
-- ============================================================

-- ============================================================
-- PHẦN I: TẠO BẢNG (DDL)
-- ============================================================

-- ── I.1 RBAC & NHÂN SỰ ──────────────────────────────────────
CREATE TABLE NHOM (
    MANHOM   VARCHAR2(10)  PRIMARY KEY,
    TENNHOM  NVARCHAR2(100)
);

CREATE TABLE VAITRO (
    MAVAITRO  VARCHAR2(10)  PRIMARY KEY,
    TENVAITRO NVARCHAR2(100)
);

CREATE TABLE NHOM_VAITRO (
    MANHOM   VARCHAR2(10),
    MAVAITRO VARCHAR2(10),
    CONSTRAINT PK_NHOM_VAITRO PRIMARY KEY (MANHOM, MAVAITRO),
    CONSTRAINT FK_NVT_NHOM    FOREIGN KEY (MANHOM)   REFERENCES NHOM(MANHOM),
    CONSTRAINT FK_NVT_VAITRO  FOREIGN KEY (MAVAITRO) REFERENCES VAITRO(MAVAITRO)
);

CREATE TABLE TAI_KHOAN (
    MATK      VARCHAR2(10)  PRIMARY KEY,
    MANHOM    VARCHAR2(10),
    USERNAME  VARCHAR2(50)  UNIQUE,
    PASSWORD  VARCHAR2(255),
    TRANGTHAI NUMBER(1)     DEFAULT 1,   -- 1: Hoạt động | 0: Bị khóa
    CONSTRAINT FK_TK_NHOM FOREIGN KEY (MANHOM) REFERENCES NHOM(MANHOM)
);

CREATE TABLE CHUC_VU (
    MACV  VARCHAR2(10)  PRIMARY KEY,
    TENCV NVARCHAR2(100)
);

CREATE TABLE NHAN_SU (
    MANS       VARCHAR2(10)  PRIMARY KEY,
    MATK       VARCHAR2(10)  UNIQUE,
    MACV       VARCHAR2(10),
    CCCD       VARCHAR2(12),
    HOTEN      NVARCHAR2(100),
    NGAYSINH   DATE,
    GIOITINH   NVARCHAR2(10),
    SDT        VARCHAR2(15),
    DIACHI     NVARCHAR2(255),
    CHUYENKHOA NVARCHAR2(100) NULL,
    IS_DELETED NUMBER(1)      DEFAULT 0,
    CONSTRAINT FK_NS_TK FOREIGN KEY (MATK) REFERENCES TAI_KHOAN(MATK),
    CONSTRAINT FK_NS_CV FOREIGN KEY (MACV) REFERENCES CHUC_VU(MACV)
);

-- Chi tiết chuyên môn/chứng chỉ — áp dụng Bác sĩ + Kỹ thuật viên
-- 1 nhân sự chỉ có 1 dòng chi tiết kỹ thuật (PK = MANS)
CREATE TABLE CHI_TIET_KY_THUAT (
    MANS                 VARCHAR2(10)  PRIMARY KEY,
    CHUYEN_NGANH         NVARCHAR2(100),
    CHUNG_CHI_HANH_NGHE  NVARCHAR2(100),   -- Số chứng chỉ hành nghề
    NAM_CAP_CHUNG_CHI    NUMBER(4),
    NOI_CAP              NVARCHAR2(200),
    KINH_NGHIEM_NAM      NUMBER(2)     DEFAULT 0,
    GHI_CHU              NVARCHAR2(500),
    CONSTRAINT FK_CTKT_NS FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS)
);

-- Lịch làm việc bác sĩ/kỹ thuật viên
CREATE TABLE LICH_LAM_VIEC (
    MALLV        VARCHAR2(10)  PRIMARY KEY,
    MANS         VARCHAR2(10)  NOT NULL,
    NGAY_LAM     DATE          NOT NULL,
    GIO_BAT_DAU  NUMBER(4,2)   NOT NULL,   -- 8.0 = 8:00, 13.5 = 13:30
    GIO_KET_THUC NUMBER(4,2)   NOT NULL,
    IS_NGHI      NUMBER(1)     DEFAULT 0,
    CONSTRAINT FK_LLV_NS  FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS),
    CONSTRAINT CK_LLV_GIO CHECK (GIO_BAT_DAU < GIO_KET_THUC)
);

-- ── I.2 KHÁCH HÀNG & Y KHOA ─────────────────────────────────
CREATE TABLE KHACH_HANG (
    MAKH        VARCHAR2(10)  PRIMARY KEY,
    MATK        VARCHAR2(10)  UNIQUE NULL,
    CCCD        VARCHAR2(12),
    HOTEN       NVARCHAR2(100),
    NGAYSINH    DATE,
    GIOITINH    NVARCHAR2(10),
    SDT         VARCHAR2(15)  UNIQUE,
    DIACHI      NVARCHAR2(255),
    DIEMTICHLUY NUMBER        DEFAULT 0,
    IS_DELETED  NUMBER(1)     DEFAULT 0,
    CONSTRAINT FK_KH_TK FOREIGN KEY (MATK) REFERENCES TAI_KHOAN(MATK)
);

-- Gói khám (cần tạo trước LICH_HEN vì LICH_HEN FK vào đây)
CREATE TABLE GOI_KHAM (
    MAGOI     VARCHAR2(10)  PRIMARY KEY,
    TENGOI    NVARCHAR2(100) NOT NULL,
    MOTA      NVARCHAR2(500),
    GIA       NUMBER(15,2)  NOT NULL,
    THOILUONG NUMBER        DEFAULT 30,  -- phút
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE TABLE LICH_HEN (
    MALH        VARCHAR2(10)  PRIMARY KEY,
    MAKH        VARCHAR2(10),
    MANS        VARCHAR2(10),
    MAGOI       VARCHAR2(10)  NULL,
    NGAYHEN     TIMESTAMP,
    GIO_HEN     TIMESTAMP,
    LOAI_LICH   NVARCHAR2(20) DEFAULT N'Online',   -- Walk-in | Online
    TRIEU_CHUNG JSON,
    TRANGTHAI   NVARCHAR2(50),                     -- Mới | Đã khám | Đã hủy
    CONSTRAINT FK_LH_KH  FOREIGN KEY (MAKH)  REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_LH_NS  FOREIGN KEY (MANS)  REFERENCES NHAN_SU(MANS),
    CONSTRAINT FK_LH_GOI FOREIGN KEY (MAGOI) REFERENCES GOI_KHAM(MAGOI)
);

CREATE TABLE HANG_CHO (
    MAHC           VARCHAR2(10)  PRIMARY KEY,
    MAKH           VARCHAR2(10),
    TEN_KHACH      NVARCHAR2(100),
    SO_THU_TU      NUMBER        NOT NULL,
    LOAI_KHACH     NVARCHAR2(20) DEFAULT N'Walk-in',
    MALH           VARCHAR2(10)  NULL,
    MANS_PHAN_CONG VARCHAR2(10)  NULL,
    TRANG_THAI     NVARCHAR2(30) DEFAULT N'Đang chờ',
    GIO_DANG_KY    TIMESTAMP     DEFAULT SYSTIMESTAMP,
    GIO_VAO_KHAM   TIMESTAMP     NULL,
    GHI_CHU        NVARCHAR2(255),
    CONSTRAINT FK_HC_KH FOREIGN KEY (MAKH)           REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HC_LH FOREIGN KEY (MALH)           REFERENCES LICH_HEN(MALH),
    CONSTRAINT FK_HC_NS FOREIGN KEY (MANS_PHAN_CONG) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE HO_SO_THI_LUC (
    MAHOSO   VARCHAR2(10)  PRIMARY KEY,
    MAKH     VARCHAR2(10),
    MANS     VARCHAR2(10),
    NGAYKHAM TIMESTAMP,
    KETLUAN  NVARCHAR2(255),
    CONSTRAINT FK_HS_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HS_NS FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE CHI_TIET_THI_LUC (
    MAHOSO        VARCHAR2(10),
    MAT           CHAR(1),          -- P: Phải | T: Trái
    DOCAU_SPH     NUMBER(4,2),
    DOTRU_CYL     NUMBER(4,2),
    TRUC_AX       NUMBER(3),
    KHOANGCACH_PD NUMBER(3,1),
    DOCONG_ADD    NUMBER(4,2),      -- NULL nếu không lão thị
    CONSTRAINT PK_CTTTL    PRIMARY KEY (MAHOSO, MAT),
    CONSTRAINT FK_CTTTL_HS FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO)
);

CREATE TABLE AUDIT_HOSO_THILUC (
    MAAUDIT         VARCHAR2(20)  PRIMARY KEY,
    MAHOSO          VARCHAR2(10),
    OLD_KETLUAN     NVARCHAR2(255),
    NEW_KETLUAN     NVARCHAR2(255),
    THOI_GIAN       TIMESTAMP     DEFAULT SYSTIMESTAMP,
    NGUOI_THUC_HIEN VARCHAR2(50)
);

-- Rating bác sĩ sau mỗi lần khám (1 hồ sơ = 1 đánh giá)
CREATE TABLE DANH_GIA (
    MADG             VARCHAR2(10)  PRIMARY KEY,
    MAHOSO           VARCHAR2(10)  NOT NULL,
    MAKH             VARCHAR2(10)  NOT NULL,
    MANS             VARCHAR2(10)  NOT NULL,
    SO_SAO           NUMBER(1)     NOT NULL,
    NOI_DUNG         NVARCHAR2(500),
    PHAN_HOI_CHI_TIET JSON,
    NGAY_DG          TIMESTAMP     DEFAULT SYSTIMESTAMP,
    IS_HIDDEN        NUMBER(1)     DEFAULT 0,
    CONSTRAINT PK_DG        PRIMARY KEY (MADG),
    CONSTRAINT UK_DG_MAHOSO UNIQUE (MAHOSO),    -- 1 hồ sơ chỉ 1 đánh giá
    CONSTRAINT CK_DG_SAO    CHECK (SO_SAO BETWEEN 1 AND 5),
    CONSTRAINT FK_DG_HS     FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_DG_KH     FOREIGN KEY (MAKH)   REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_DG_NS     FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS)
);

-- ── I.3 SẢN PHẨM & KÊ ĐƠN ──────────────────────────────────
CREATE TABLE LOAI_SAN_PHAM (
    MALOAI  VARCHAR2(10)  PRIMARY KEY,
    TENLOAI NVARCHAR2(100)
);

CREATE TABLE SAN_PHAM (
    MASP              VARCHAR2(10)  PRIMARY KEY,
    MALOAI            VARCHAR2(10),
    TENSP             NVARCHAR2(100),
    DONVITINH         NVARCHAR2(20),
    LATHUOC           NUMBER(1),               -- 1: Thuốc/TPCN | 0: Kính/Thiết bị
    GIABAN            NUMBER(15,2),
    TON_KHO_TOI_THIEU NUMBER        DEFAULT 0,
    DON_VI_TINH_KHO   NVARCHAR2(20) NULL,
    CONSTRAINT FK_SP_LOAI FOREIGN KEY (MALOAI) REFERENCES LOAI_SAN_PHAM(MALOAI)
);

-- Phiếu kê đơn — Bác sĩ lập sau khám, KTV dùng để cắt kính
CREATE TABLE PHIEU_KE_DON (
    MADON     VARCHAR2(10)  PRIMARY KEY,
    MAHOSO    VARCHAR2(10),
    MANS      VARCHAR2(10),
    NGAYKEDON DATE,
    LOIDAN    NVARCHAR2(255),
    CONSTRAINT FK_PKD_HS FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_PKD_NS FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS)
);

-- Chi tiết đơn: thuốc (LIEUDUNG/CACHDUNG bắt buộc) hoặc kính (NULL)
CREATE TABLE CT_KE_DON (
    MADON    VARCHAR2(10),
    MASP     VARCHAR2(10),
    SOLUONG  NUMBER,
    LIEUDUNG NVARCHAR2(100) NULL,
    CACHDUNG NVARCHAR2(100) NULL,
    CONSTRAINT PK_CTKD     PRIMARY KEY (MADON, MASP),
    CONSTRAINT FK_CTKD_PKD FOREIGN KEY (MADON) REFERENCES PHIEU_KE_DON(MADON),
    CONSTRAINT FK_CTKD_SP  FOREIGN KEY (MASP)  REFERENCES SAN_PHAM(MASP)
);

-- Xử lý kính — KTV nhận đơn, cắt kính, cập nhật trạng thái
CREATE TABLE XU_LY_KINH (
    MAXL            VARCHAR2(10)  PRIMARY KEY,
    MADON           VARCHAR2(10)  NOT NULL,
    THONG_SO_KINH   JSON,                    -- SPH/CYL/AX/ADD từ đơn bác sĩ
    TRANG_THAI      NVARCHAR2(30) DEFAULT N'Chờ xử lý',
    -- Chờ xử lý | Đang cắt | Hoàn thành | Lỗi - làm lại
    NGAY_BAT_DAU    TIMESTAMP     NULL,
    NGAY_HOAN_THANH TIMESTAMP     NULL,
    MANS_KY_THUAT   VARCHAR2(10)  NULL,      -- KTV được giao
    GHI_CHU         NVARCHAR2(255),
    CONSTRAINT FK_XLK_PKD FOREIGN KEY (MADON)          REFERENCES PHIEU_KE_DON(MADON),
    CONSTRAINT FK_XLK_NS  FOREIGN KEY (MANS_KY_THUAT)  REFERENCES NHAN_SU(MANS)
);

-- ── I.4 NHẬP KHO & LÔ HÀNG ─────────────────────────────────
CREATE TABLE NHA_CUNG_CAP (
    MANCC  VARCHAR2(10)  PRIMARY KEY,
    TENNCC NVARCHAR2(100),
    SDT    VARCHAR2(15),
    DIACHI NVARCHAR2(255)
);

-- Giao dịch tài chính với NCC (thanh toán hóa đơn NCC, trả hàng...)
CREATE TABLE GIAO_DICH_NCC (
    MAGD    VARCHAR2(10)  PRIMARY KEY,
    MANCC   VARCHAR2(10)  NOT NULL,
    LOAI    NVARCHAR2(20) NOT NULL,           -- ThanhToan | TraHang | KhacKhau
    SO_TIEN NUMBER(15,2)  NOT NULL,
    NGAY_GD TIMESTAMP     DEFAULT SYSTIMESTAMP,
    MAPN    VARCHAR2(10)  NULL,               -- Liên kết phiếu nhập nếu có
    GHI_CHU NVARCHAR2(255),
    CONSTRAINT FK_GD_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC)
);

CREATE TABLE PHIEU_NHAP (
    MAPN     VARCHAR2(10)  PRIMARY KEY,
    MANCC    VARCHAR2(10),
    MANS     VARCHAR2(10),
    NGAYNHAP TIMESTAMP,
    TONGTIEN NUMBER(15,2)  DEFAULT 0,
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHA_CUNG_CAP(MANCC),
    CONSTRAINT FK_PN_NS  FOREIGN KEY (MANS)  REFERENCES NHAN_SU(MANS)
);

-- FK vòng: GIAO_DICH_NCC.MAPN → PHIEU_NHAP (tạo sau)
ALTER TABLE GIAO_DICH_NCC ADD CONSTRAINT FK_GD_PN
    FOREIGN KEY (MAPN) REFERENCES PHIEU_NHAP(MAPN);

CREATE TABLE LO_HANG (
    MALO        VARCHAR2(10)  PRIMARY KEY,
    MASP        VARCHAR2(10),
    MAPN        VARCHAR2(10),
    NGAYSANXUAT DATE,
    NGAYHETHAN  DATE,
    SOLUONGNHAP NUMBER,
    SOLUONGTON  NUMBER,
    GIANHAP     NUMBER(15,2),
    CONSTRAINT FK_LO_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP),
    CONSTRAINT FK_LO_PN FOREIGN KEY (MAPN) REFERENCES PHIEU_NHAP(MAPN)
);

-- ── I.5 BÁN HÀNG & XUẤT KHO ─────────────────────────────────
-- Dịch vụ khám (cần tạo trước HOA_DON → CT_HOA_DON_DV)
CREATE TABLE DICH_VU_KHAM (
    MADV      VARCHAR2(10)  PRIMARY KEY,
    TENDV     NVARCHAR2(100) NOT NULL,
    GIA       NUMBER(15,2)  NOT NULL,
    MOTA      NVARCHAR2(255),
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE TABLE HOA_DON (
    MAHD       VARCHAR2(10)  PRIMARY KEY,
    MAKH       VARCHAR2(10),
    MANS       VARCHAR2(10),
    MAHOSO     VARCHAR2(10)  NULL,
    MADON      VARCHAR2(10)  NULL,            -- Liên kết phiếu kê đơn
    NGAYLAP    TIMESTAMP,
    TONGTIEN   NUMBER(15,2)  DEFAULT 0,
    TRANGTHAI  NVARCHAR2(50) DEFAULT N'Chưa thanh toán',
    IS_DELETED NUMBER(1)     DEFAULT 0,
    CONSTRAINT FK_HD_KH  FOREIGN KEY (MAKH)   REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_HD_NS  FOREIGN KEY (MANS)   REFERENCES NHAN_SU(MANS),
    CONSTRAINT FK_HD_HS  FOREIGN KEY (MAHOSO) REFERENCES HO_SO_THI_LUC(MAHOSO),
    CONSTRAINT FK_HD_PKD FOREIGN KEY (MADON)  REFERENCES PHIEU_KE_DON(MADON)
);

-- CT sản phẩm/lô hàng trong hóa đơn
CREATE TABLE CT_HOA_DON (
    MAHD    VARCHAR2(10),
    MALO    VARCHAR2(10),
    SOLUONG NUMBER,
    DONGIA  NUMBER(15,2),
    CONSTRAINT PK_CTHD    PRIMARY KEY (MAHD, MALO),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_CTHD_LO FOREIGN KEY (MALO) REFERENCES LO_HANG(MALO)
);

-- CT dịch vụ khám trong hóa đơn (song song với CT_HOA_DON)
CREATE TABLE CT_HOA_DON_DV (
    MAHD    VARCHAR2(10),
    MADV    VARCHAR2(10),
    SOLUONG NUMBER        DEFAULT 1,
    DONGIA  NUMBER(15,2),
    CONSTRAINT PK_CTHD_DV    PRIMARY KEY (MAHD, MADV),
    CONSTRAINT FK_CTHD_DV_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_CTHD_DV_DV FOREIGN KEY (MADV) REFERENCES DICH_VU_KHAM(MADV)
);

CREATE TABLE THANH_TOAN (
    MATT          VARCHAR2(10)  PRIMARY KEY,
    MAHD          VARCHAR2(10),
    NGAYTHANHTOAN TIMESTAMP,
    SOTIEN        NUMBER(15,2),
    PHUONGTHUC    NVARCHAR2(50),
    TRANGTHAI     NVARCHAR2(50),
    CONSTRAINT FK_TT_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD)
);

CREATE TABLE PHIEU_XUAT (
    MAPX     VARCHAR2(10)  PRIMARY KEY,
    MAHD     VARCHAR2(10),
    MANS     VARCHAR2(10),
    NGAYXUAT TIMESTAMP,
    CONSTRAINT FK_PX_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT FK_PX_NS FOREIGN KEY (MANS) REFERENCES NHAN_SU(MANS)
);

CREATE TABLE CT_PHIEU_XUAT (
    MAPX        VARCHAR2(10),
    MALO        VARCHAR2(10),
    SOLUONGXUAT NUMBER,
    CONSTRAINT PK_CTPX    PRIMARY KEY (MAPX, MALO),
    CONSTRAINT FK_CTPX_PX FOREIGN KEY (MAPX) REFERENCES PHIEU_XUAT(MAPX),
    CONSTRAINT FK_CTPX_LO FOREIGN KEY (MALO) REFERENCES LO_HANG(MALO)
);

-- ============================================================
-- PHẦN II: SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_HOA_DON        START WITH 1 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE SEQ_THANH_TOAN     START WITH 1 INCREMENT BY 1 NOCACHE  NOCYCLE;
CREATE SEQUENCE SEQ_LO_HANG        START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_PHIEU_NHAP     START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE SEQUENCE SEQ_PHIEU_XUAT     START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE SEQUENCE SEQ_LICH_HEN       START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE SEQUENCE SEQ_HO_SO          START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE SEQUENCE SEQ_AUDIT          START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;
CREATE SEQUENCE SEQ_LICH_LAM_VIEC  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DANH_GIA       START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_HANG_CHO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_XU_LY_KINH     START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE SEQUENCE SEQ_GIAO_DICH_NCC  START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;

-- ============================================================
-- PHẦN III: TRIGGERS AUTO-SINH MÃ
-- ============================================================
CREATE OR REPLACE TRIGGER TRG_GEN_MAHD
BEFORE INSERT ON HOA_DON FOR EACH ROW
BEGIN IF :NEW.MAHD IS NULL THEN :NEW.MAHD := 'HD' || LPAD(SEQ_HOA_DON.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MATT
BEFORE INSERT ON THANH_TOAN FOR EACH ROW
BEGIN IF :NEW.MATT IS NULL THEN :NEW.MATT := 'TT' || LPAD(SEQ_THANH_TOAN.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MALO
BEFORE INSERT ON LO_HANG FOR EACH ROW
BEGIN IF :NEW.MALO IS NULL THEN :NEW.MALO := 'LO' || LPAD(SEQ_LO_HANG.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAPN
BEFORE INSERT ON PHIEU_NHAP FOR EACH ROW
BEGIN IF :NEW.MAPN IS NULL THEN :NEW.MAPN := 'PN' || LPAD(SEQ_PHIEU_NHAP.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAPX
BEFORE INSERT ON PHIEU_XUAT FOR EACH ROW
BEGIN IF :NEW.MAPX IS NULL THEN :NEW.MAPX := 'PX' || LPAD(SEQ_PHIEU_XUAT.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MALH
BEFORE INSERT ON LICH_HEN FOR EACH ROW
BEGIN IF :NEW.MALH IS NULL THEN :NEW.MALH := 'LH' || LPAD(SEQ_LICH_HEN.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAHOSO
BEFORE INSERT ON HO_SO_THI_LUC FOR EACH ROW
BEGIN IF :NEW.MAHOSO IS NULL THEN :NEW.MAHOSO := 'HS' || LPAD(SEQ_HO_SO.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MALLV
BEFORE INSERT ON LICH_LAM_VIEC FOR EACH ROW
BEGIN IF :NEW.MALLV IS NULL THEN :NEW.MALLV := 'LV' || LPAD(SEQ_LICH_LAM_VIEC.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MADG
BEFORE INSERT ON DANH_GIA FOR EACH ROW
BEGIN IF :NEW.MADG IS NULL THEN :NEW.MADG := 'DG' || LPAD(SEQ_DANH_GIA.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAHC
BEFORE INSERT ON HANG_CHO FOR EACH ROW
BEGIN
    IF :NEW.MAHC IS NULL THEN :NEW.MAHC := 'HC' || LPAD(SEQ_HANG_CHO.NEXTVAL,6,'0'); END IF;
    IF :NEW.SO_THU_TU IS NULL THEN
        SELECT NVL(MAX(SO_THU_TU),0)+1 INTO :NEW.SO_THU_TU
        FROM HANG_CHO WHERE TRUNC(GIO_DANG_KY) = TRUNC(SYSDATE);
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAXL
BEFORE INSERT ON XU_LY_KINH FOR EACH ROW
BEGIN IF :NEW.MAXL IS NULL THEN :NEW.MAXL := 'XL' || LPAD(SEQ_XU_LY_KINH.NEXTVAL,6,'0'); END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAGD
BEFORE INSERT ON GIAO_DICH_NCC FOR EACH ROW
BEGIN IF :NEW.MAGD IS NULL THEN :NEW.MAGD := 'GD' || LPAD(SEQ_GIAO_DICH_NCC.NEXTVAL,6,'0'); END IF; END;
/

-- ============================================================
-- PHẦN IV: TRIGGERS NGHIỆP VỤ
-- ============================================================

-- 1. Nhân Sự — tuổi >= 18, chặn trùng MATK
CREATE OR REPLACE TRIGGER TRG_VALIDATE_NHAN_SU
BEFORE INSERT OR UPDATE ON NHAN_SU
FOR EACH ROW
DECLARE
    v_tuoi  NUMBER;
    v_count NUMBER;
BEGIN
    v_tuoi := FLOOR(MONTHS_BETWEEN(SYSDATE, :NEW.NGAYSINH) / 12);
    IF v_tuoi < 18 THEN
        RAISE_APPLICATION_ERROR(-20010, 'LỖI: Nhân viên [' || :NEW.HOTEN || '] chưa đủ 18 tuổi!');
    END IF;
    IF INSERTING AND :NEW.MATK IS NOT NULL THEN
        SELECT COUNT(*) INTO v_count FROM NHAN_SU WHERE MATK = :NEW.MATK;
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20009, 'LỖI: Tài khoản đã được gán cho nhân sự khác!');
        END IF;
    END IF;
END;
/

-- 2. Khách Hàng — validate SĐT, chặn xóa cứng
CREATE OR REPLACE TRIGGER TRG_VALIDATE_KHACH_HANG
BEFORE INSERT OR UPDATE OR DELETE ON KHACH_HANG
FOR EACH ROW
DECLARE v_count NUMBER;
BEGIN
    IF INSERTING OR UPDATING THEN
        IF NOT REGEXP_LIKE(:NEW.SDT, '^[0-9]{9,11}$') THEN
            RAISE_APPLICATION_ERROR(-20013, 'LỖI: SĐT không hợp lệ (9-11 chữ số)!');
        END IF;
    END IF;
    IF DELETING THEN
        SELECT COUNT(*) INTO v_count FROM LICH_HEN WHERE MAKH = :OLD.MAKH AND TRANGTHAI = N'Mới';
        IF v_count > 0 THEN
            RAISE_APPLICATION_ERROR(-20050, 'LỖI: KH đang có lịch hẹn chờ — dùng Soft Delete!');
        END IF;
    END IF;
END;
/

-- 3. Lịch Hẹn — kiểm tra bác sĩ có lịch làm việc + không trùng slot
CREATE OR REPLACE TRIGGER TRG_VALIDATE_LICH_HEN
FOR INSERT OR UPDATE ON LICH_HEN
COMPOUND TRIGGER
    TYPE t_mahd_list IS TABLE OF VARCHAR2(10);
    v_mahd_arr t_mahd_list := t_mahd_list();

    BEFORE EACH ROW IS
        v_ca_lam NUMBER;
        v_ton_kh NUMBER;
        v_ton_ns NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_ton_kh FROM KHACH_HANG WHERE MAKH = :NEW.MAKH AND IS_DELETED = 0;
        IF v_ton_kh = 0 THEN RAISE_APPLICATION_ERROR(-20032, 'LỖI: Khách hàng không tồn tại!'); END IF;

        SELECT COUNT(*) INTO v_ton_ns FROM NHAN_SU WHERE MANS = :NEW.MANS AND IS_DELETED = 0;
        IF v_ton_ns = 0 THEN RAISE_APPLICATION_ERROR(-20033, 'LỖI: Bác sĩ không tồn tại hoặc đã nghỉ!'); END IF;

        SELECT COUNT(*) INTO v_ca_lam FROM LICH_LAM_VIEC
        WHERE MANS = :NEW.MANS AND NGAY_LAM = TRUNC(:NEW.NGAYHEN) AND IS_NGHI = 0;
        IF v_ca_lam = 0 THEN RAISE_APPLICATION_ERROR(-20030, 'LỖI: Bác sĩ không có lịch làm việc ngày này!'); END IF;

        IF :NEW.GIO_HEN IS NOT NULL THEN
            -- Lưu mã lịch hẹn để sau kiểm tra trùng (xử lý sau)
            v_mahd_arr.EXTEND;
            v_mahd_arr(v_mahd_arr.LAST) := :NEW.MALH;
        END IF;
    END BEFORE EACH ROW;

    AFTER STATEMENT IS
        v_trung NUMBER;
    BEGIN
        FOR i IN 1 .. v_mahd_arr.COUNT LOOP
            -- Kiểm tra trùng slot
            SELECT COUNT(*) INTO v_trung
            FROM LICH_HEN
            WHERE MANS = (SELECT MANS FROM LICH_HEN WHERE MALH = v_mahd_arr(i))
              AND GIO_HEN = (SELECT GIO_HEN FROM LICH_HEN WHERE MALH = v_mahd_arr(i))
              AND TRANGTHAI != N'Đã hủy'
              AND MALH != v_mahd_arr(i);
            IF v_trung > 0 THEN
                RAISE_APPLICATION_ERROR(-20031, 'LỖI: Bác sĩ đã có lịch slot này!');
            END IF;
        END LOOP;
    END AFTER STATEMENT;
END TRG_VALIDATE_LICH_HEN;
/
-- 4. Hồ Sơ Thị Lực — chỉ Bác sĩ hoặc Kỹ thuật viên mắt kính
CREATE OR REPLACE TRIGGER TRG_VALIDATE_HO_SO
BEFORE INSERT OR UPDATE ON HO_SO_THI_LUC
FOR EACH ROW
DECLARE v_tencv CHUC_VU.TENCV%TYPE;
BEGIN
    SELECT cv.TENCV INTO v_tencv FROM NHAN_SU ns JOIN CHUC_VU cv ON ns.MACV = cv.MACV WHERE ns.MANS = :NEW.MANS;
    IF v_tencv NOT IN (N'Bác sĩ', N'Kỹ thuật viên mắt kính') THEN
        RAISE_APPLICATION_ERROR(-20001, 'LỖI: Chỉ Bác sĩ/KTV mắt kính được lập Hồ Sơ!');
    END IF;
END;
/

-- 5. Hóa Đơn — phân quyền Thu ngân/Quản lý, chặn sửa HĐ đã TT
CREATE OR REPLACE TRIGGER TRG_VALIDATE_HOA_DON
BEFORE INSERT OR UPDATE OR DELETE ON HOA_DON
FOR EACH ROW
DECLARE v_tencv CHUC_VU.TENCV%TYPE;
BEGIN
    IF INSERTING OR UPDATING THEN
        SELECT cv.TENCV INTO v_tencv FROM NHAN_SU ns JOIN CHUC_VU cv ON ns.MACV = cv.MACV WHERE ns.MANS = :NEW.MANS;
        IF v_tencv NOT IN (N'Thu ngân', N'Quản lý') THEN
            RAISE_APPLICATION_ERROR(-20003, 'LỖI: Chỉ Thu ngân/Quản lý tạo Hóa Đơn!');
        END IF;
    END IF;
    IF UPDATING OR DELETING THEN
        IF :OLD.TRANGTHAI = N'Đã thanh toán' THEN
            RAISE_APPLICATION_ERROR(-20007, 'LỖI: Hóa đơn đã thanh toán, không can thiệp!');
        END IF;
    END IF;
END;
/

-- 6. CT Hóa Đơn SP — trừ tồn kho, kiểm tra HSD, tính tiền
CREATE OR REPLACE TRIGGER TRG_CT_HOA_DON_SP
FOR INSERT OR UPDATE OR DELETE ON CT_HOA_DON
COMPOUND TRIGGER
    v_ton NUMBER; v_hsd DATE;
    BEFORE EACH ROW IS
    BEGIN
        FOR rec IN (SELECT TRANGTHAI FROM HOA_DON WHERE MAHD = NVL(:NEW.MAHD, :OLD.MAHD)) LOOP
            IF rec.TRANGTHAI IN (N'Đã thanh toán', N'Đã hủy') THEN
                RAISE_APPLICATION_ERROR(-20033, 'CTHD: Hóa đơn đã đóng!');
            END IF;
        END LOOP;
        IF INSERTING OR UPDATING THEN
            SELECT SOLUONGTON, NGAYHETHAN INTO v_ton, v_hsd FROM LO_HANG WHERE MALO = :NEW.MALO;
            IF v_hsd < TRUNC(SYSDATE) THEN RAISE_APPLICATION_ERROR(-20006, 'CTHD: Lô hàng đã hết hạn!'); END IF;
            IF :NEW.SOLUONG <= 0 THEN RAISE_APPLICATION_ERROR(-20014, 'CTHD: Số lượng phải > 0!'); END IF;
            IF :NEW.SOLUONG > (CASE WHEN UPDATING THEN v_ton + :OLD.SOLUONG ELSE v_ton END) THEN
                RAISE_APPLICATION_ERROR(-20005, 'CTHD: Không đủ hàng trong kho!');
            END IF;
        END IF;
    END BEFORE EACH ROW;
    AFTER EACH ROW IS
    BEGIN
        IF INSERTING THEN
            UPDATE LO_HANG SET SOLUONGTON = SOLUONGTON - :NEW.SOLUONG WHERE MALO = :NEW.MALO;
            UPDATE HOA_DON  SET TONGTIEN  = NVL(TONGTIEN,0) + (:NEW.SOLUONG * :NEW.DONGIA) WHERE MAHD = :NEW.MAHD;
        ELSIF UPDATING THEN
            UPDATE LO_HANG SET SOLUONGTON = SOLUONGTON + :OLD.SOLUONG - :NEW.SOLUONG WHERE MALO = :NEW.MALO;
            UPDATE HOA_DON  SET TONGTIEN  = NVL(TONGTIEN,0) - (:OLD.SOLUONG * :OLD.DONGIA) + (:NEW.SOLUONG * :NEW.DONGIA) WHERE MAHD = :NEW.MAHD;
        ELSIF DELETING THEN
            UPDATE LO_HANG SET SOLUONGTON = SOLUONGTON + :OLD.SOLUONG WHERE MALO = :OLD.MALO;
            UPDATE HOA_DON  SET TONGTIEN  = NVL(TONGTIEN,0) - (:OLD.SOLUONG * :OLD.DONGIA) WHERE MAHD = :OLD.MAHD;
        END IF;
    END AFTER EACH ROW;
END TRG_CT_HOA_DON_SP;
/

-- 7. CT Hóa Đơn DV — tính tiền dịch vụ
CREATE OR REPLACE TRIGGER TRG_CT_HOA_DON_DV
FOR INSERT OR UPDATE OR DELETE ON CT_HOA_DON_DV
COMPOUND TRIGGER
    AFTER EACH ROW IS
    BEGIN
        IF INSERTING THEN
            UPDATE HOA_DON SET TONGTIEN = NVL(TONGTIEN,0) + (:NEW.SOLUONG * :NEW.DONGIA) WHERE MAHD = :NEW.MAHD;
        ELSIF UPDATING THEN
            UPDATE HOA_DON SET TONGTIEN = NVL(TONGTIEN,0) - (:OLD.SOLUONG * :OLD.DONGIA) + (:NEW.SOLUONG * :NEW.DONGIA) WHERE MAHD = :NEW.MAHD;
        ELSIF DELETING THEN
            UPDATE HOA_DON SET TONGTIEN = NVL(TONGTIEN,0) - (:OLD.SOLUONG * :OLD.DONGIA) WHERE MAHD = :OLD.MAHD;
        END IF;
    END AFTER EACH ROW;
END TRG_CT_HOA_DON_DV;
/

-- 8. Phiếu Nhập — phân quyền Thủ kho/Quản lý
CREATE OR REPLACE TRIGGER TRG_PHIEU_NHAP
BEFORE INSERT OR UPDATE ON PHIEU_NHAP
FOR EACH ROW
DECLARE
    v_tencv    CHUC_VU.TENCV%TYPE;
    v_lo_daban NUMBER;
BEGIN
    SELECT cv.TENCV INTO v_tencv FROM NHAN_SU ns JOIN CHUC_VU cv ON ns.MACV = cv.MACV WHERE ns.MANS = :NEW.MANS;
    IF v_tencv NOT IN (N'Thủ kho', N'Quản lý') THEN
        RAISE_APPLICATION_ERROR(-20004, 'LỖI: Chỉ Thủ kho/Quản lý lập phiếu nhập!');
    END IF;
    IF UPDATING THEN
        SELECT COUNT(*) INTO v_lo_daban FROM LO_HANG WHERE MAPN = :OLD.MAPN AND SOLUONGTON < SOLUONGNHAP;
        IF v_lo_daban > 0 THEN RAISE_APPLICATION_ERROR(-20015, 'LỖI: Phiếu đã xuất bán, không thể sửa!'); END IF;
    END IF;
END;
/

-- 9. Thanh Toán — FIX: Sử dụng Array trong Compound Trigger tránh Mutating Table
CREATE OR REPLACE TRIGGER TRG_THANH_TOAN
FOR INSERT OR UPDATE ON THANH_TOAN
COMPOUND TRIGGER
    TYPE t_mahd_list IS TABLE OF VARCHAR2(10);
    v_mahd_arr t_mahd_list := t_mahd_list();

    BEFORE EACH ROW IS
        v_tong_hd NUMBER;
    BEGIN
        SELECT TONGTIEN INTO v_tong_hd FROM HOA_DON WHERE MAHD = :NEW.MAHD;
        IF :NEW.SOTIEN <= 0 OR :NEW.SOTIEN > v_tong_hd THEN
            RAISE_APPLICATION_ERROR(-20018, 'LỖI: Số tiền thanh toán không hợp lệ!');
        END IF;
    END BEFORE EACH ROW;

    AFTER EACH ROW IS
    BEGIN
        IF :NEW.TRANGTHAI = N'Thành công' THEN
            v_mahd_arr.EXTEND;
            v_mahd_arr(v_mahd_arr.LAST) := :NEW.MAHD;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_tong_hd NUMBER;
        v_da_tt   NUMBER;
        v_makh    VARCHAR2(10);
    BEGIN
        FOR i IN 1 .. v_mahd_arr.COUNT LOOP
            SELECT NVL(SUM(SOTIEN),0) INTO v_da_tt
            FROM THANH_TOAN WHERE MAHD = v_mahd_arr(i) AND TRANGTHAI = N'Thành công';

            SELECT TONGTIEN, MAKH INTO v_tong_hd, v_makh
            FROM HOA_DON WHERE MAHD = v_mahd_arr(i);

            IF v_da_tt >= v_tong_hd THEN
                UPDATE HOA_DON SET TRANGTHAI = N'Đã thanh toán' WHERE MAHD = v_mahd_arr(i);
                -- Cộng điểm thưởng (1 điểm/100k)
                UPDATE KHACH_HANG
                SET DIEMTICHLUY = NVL(DIEMTICHLUY,0) + FLOOR(v_tong_hd / 100000)
                WHERE MAKH = v_makh;
                -- Ghi lịch sử điểm
                INSERT INTO LICH_SU_DIEM(MALSD, MAKH, LOAI, SO_DIEM, LY_DO, MAHD)
                VALUES (NULL, v_makh, N'Cong', FLOOR(v_tong_hd / 100000), N'Tích điểm từ hóa đơn', v_mahd_arr(i));
            END IF;
        END LOOP;
    END AFTER STATEMENT;
END TRG_THANH_TOAN;
/
-- 10. Audit Hồ Sơ — ghi log mọi thay đổi kết luận
CREATE OR REPLACE TRIGGER TRG_AUDIT_HO_SO
AFTER UPDATE OF KETLUAN ON HO_SO_THI_LUC
FOR EACH ROW
BEGIN
    IF NVL(:OLD.KETLUAN,' ') != NVL(:NEW.KETLUAN,' ') THEN
        INSERT INTO AUDIT_HOSO_THILUC(MAAUDIT, MAHOSO, OLD_KETLUAN, NEW_KETLUAN, NGUOI_THUC_HIEN)
        VALUES ('AUD' || LPAD(SEQ_AUDIT.NEXTVAL,9,'0'), :OLD.MAHOSO, :OLD.KETLUAN, :NEW.KETLUAN, USER);
    END IF;
END;
/

-- 11. Lô Hàng — set tồn = nhập, cộng TONGTIEN phiếu nhập
CREATE OR REPLACE TRIGGER TRG_LO_HANG
FOR INSERT OR UPDATE ON LO_HANG
COMPOUND TRIGGER
    BEFORE EACH ROW IS
    BEGIN
        IF INSERTING THEN :NEW.SOLUONGTON := :NEW.SOLUONGNHAP; END IF;
        IF :NEW.NGAYHETHAN <= TRUNC(SYSDATE) THEN RAISE_APPLICATION_ERROR(-20029, 'LỖI: Lô hàng đã hết hạn!'); END IF;
    END BEFORE EACH ROW;
    AFTER EACH ROW IS
    BEGIN
        IF INSERTING THEN
            UPDATE PHIEU_NHAP SET TONGTIEN = NVL(TONGTIEN,0) + (:NEW.SOLUONGNHAP * :NEW.GIANHAP) WHERE MAPN = :NEW.MAPN;
        ELSIF UPDATING THEN
            UPDATE PHIEU_NHAP SET TONGTIEN = NVL(TONGTIEN,0) - (:OLD.SOLUONGNHAP * :OLD.GIANHAP) + (:NEW.SOLUONGNHAP * :NEW.GIANHAP) WHERE MAPN = :NEW.MAPN;
        END IF;
    END AFTER EACH ROW;
END TRG_LO_HANG;
/

-- 12. Kê Đơn — chỉ Bác sĩ hoặc Kỹ thuật viên
CREATE OR REPLACE TRIGGER TRG_VALIDATE_KE_DON
BEFORE INSERT OR UPDATE ON PHIEU_KE_DON
FOR EACH ROW
DECLARE v_tencv CHUC_VU.TENCV%TYPE;
BEGIN
    SELECT cv.TENCV INTO v_tencv FROM NHAN_SU ns JOIN CHUC_VU cv ON ns.MACV = cv.MACV WHERE ns.MANS = :NEW.MANS;
    IF v_tencv NOT IN (N'Bác sĩ', N'Kỹ thuật viên mắt kính') THEN
        RAISE_APPLICATION_ERROR(-20025, 'LỖI: Chỉ Bác sĩ/KTV được Kê Đơn!');
    END IF;
END;
/

-- 13. Hủy Hóa Đơn — hoàn tồn kho
CREATE OR REPLACE TRIGGER TRG_HOA_DON_HUY
AFTER UPDATE OF TRANGTHAI ON HOA_DON
FOR EACH ROW
WHEN (NEW.TRANGTHAI = N'Đã hủy' AND OLD.TRANGTHAI != N'Đã hủy')
BEGIN
    FOR rec IN (SELECT MALO, SOLUONG FROM CT_HOA_DON WHERE MAHD = :NEW.MAHD) LOOP
        UPDATE LO_HANG SET SOLUONGTON = SOLUONGTON + rec.SOLUONG WHERE MALO = rec.MALO;
    END LOOP;
END;
/
CREATE OR REPLACE TRIGGER TRG_GEN_MAHC
FOR INSERT ON HANG_CHO
COMPOUND TRIGGER
    v_max_stt NUMBER := 0;

    BEFORE STATEMENT IS
    BEGIN
        -- Lấy STT lớn nhất của ngày hôm nay một lần duy nhất để tránh ORA-04091
        SELECT NVL(MAX(SO_THU_TU), 0) INTO v_max_stt
        FROM HANG_CHO WHERE TRUNC(GIO_DANG_KY) = TRUNC(SYSDATE);
    END BEFORE STATEMENT;

    BEFORE EACH ROW IS
    BEGIN
        IF :NEW.MAHC IS NULL THEN 
            :NEW.MAHC := 'HC' || LPAD(SEQ_HANG_CHO.NEXTVAL,6,'0'); 
        END IF;
        
        IF :NEW.SO_THU_TU IS NULL THEN
            v_max_stt := v_max_stt + 1;
            :NEW.SO_THU_TU := v_max_stt;
        END IF;
    END BEFORE EACH ROW;
END TRG_GEN_MAHC;
/



-- ============================================================
-- PHẦN V: STORED PROCEDURES
-- ============================================================

-- SP 1: Lưu hồ sơ khám bệnh
CREATE OR REPLACE PROCEDURE SP_LUU_HOSO_KHAM_BENH (
    p_mahoso       IN OUT VARCHAR2,
    p_makh         IN VARCHAR2, p_mans IN VARCHAR2, p_ketluan IN NVARCHAR2,
    p_mat_trai_sph IN NUMBER, p_mat_trai_cyl IN NUMBER, p_mat_trai_ax IN NUMBER, p_docong_trai IN NUMBER DEFAULT NULL,
    p_mat_phai_sph IN NUMBER, p_mat_phai_cyl IN NUMBER, p_mat_phai_ax IN NUMBER, p_docong_phai IN NUMBER DEFAULT NULL,
    p_pd IN NUMBER, p_madon_out OUT VARCHAR2
) AS
    v_madon VARCHAR2(20);
BEGIN
    INSERT INTO HO_SO_THI_LUC(MAHOSO, MAKH, MANS, NGAYKHAM, KETLUAN)
    VALUES (p_mahoso, p_makh, p_mans, SYSTIMESTAMP, p_ketluan) RETURNING MAHOSO INTO p_mahoso;

    INSERT INTO CHI_TIET_THI_LUC(MAHOSO, MAT, DOCAU_SPH, DOTRU_CYL, TRUC_AX, KHOANGCACH_PD, DOCONG_ADD)
    VALUES (p_mahoso,'T', p_mat_trai_sph, p_mat_trai_cyl, p_mat_trai_ax, p_pd, p_docong_trai);
    INSERT INTO CHI_TIET_THI_LUC(MAHOSO, MAT, DOCAU_SPH, DOTRU_CYL, TRUC_AX, KHOANGCACH_PD, DOCONG_ADD)
    VALUES (p_mahoso,'P', p_mat_phai_sph, p_mat_phai_cyl, p_mat_phai_ax, p_pd, p_docong_phai);

    v_madon := 'KD_' || p_mahoso;
    INSERT INTO PHIEU_KE_DON(MADON, MAHOSO, MANS, NGAYKEDON) VALUES (v_madon, p_mahoso, p_mans, SYSDATE);
    p_madon_out := v_madon;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_LUU_HOSO_KHAM_BENH;
/

-- SP 2: Chốt thanh toán & xuất kho
CREATE OR REPLACE PROCEDURE SP_CHOT_THANH_TOAN_HOA_DON (
    p_mahd IN VARCHAR2, p_phuongthuc IN NVARCHAR2, p_matt_out OUT VARCHAR2
) AS
    v_tongtien NUMBER; v_mans VARCHAR2(10); v_mapx VARCHAR2(20); v_matt VARCHAR2(10);
BEGIN
    SELECT TONGTIEN, MANS INTO v_tongtien, v_mans FROM HOA_DON WHERE MAHD = p_mahd;
    INSERT INTO THANH_TOAN(MATT, MAHD, NGAYTHANHTOAN, SOTIEN, PHUONGTHUC, TRANGTHAI)
    VALUES (NULL, p_mahd, SYSTIMESTAMP, v_tongtien, p_phuongthuc, N'Thành công') RETURNING MATT INTO v_matt;
    p_matt_out := v_matt;
    INSERT INTO PHIEU_XUAT(MAPX, MAHD, MANS, NGAYXUAT)
    VALUES (NULL, p_mahd, v_mans, SYSTIMESTAMP) RETURNING MAPX INTO v_mapx;
    INSERT INTO CT_PHIEU_XUAT(MAPX, MALO, SOLUONGXUAT)
    SELECT v_mapx, MALO, SOLUONG FROM CT_HOA_DON WHERE MAHD = p_mahd;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_CHOT_THANH_TOAN_HOA_DON;
/

-- SP 3: Nhập kho lô hàng
CREATE OR REPLACE PROCEDURE SP_NHAP_KHO_LO_HANG (
    p_mapn IN OUT VARCHAR2, p_mancc IN VARCHAR2, p_mans IN VARCHAR2,
    p_malo IN OUT VARCHAR2, p_masp IN VARCHAR2,
    p_ngaysx IN DATE, p_ngayhethan IN DATE,
    p_soluongnhap IN NUMBER, p_gianhap IN NUMBER,
    p_tongtien_out OUT NUMBER
) AS
    v_existing NUMBER; v_tongtien NUMBER;
BEGIN
    IF p_mapn IS NULL THEN
        INSERT INTO PHIEU_NHAP(MAPN,MANCC,MANS,NGAYNHAP,TONGTIEN)
        VALUES (NULL,p_mancc,p_mans,SYSTIMESTAMP,0) RETURNING MAPN INTO p_mapn;
    ELSE
        SELECT COUNT(*) INTO v_existing FROM PHIEU_NHAP WHERE MAPN = p_mapn;
        IF v_existing = 0 THEN
            INSERT INTO PHIEU_NHAP(MAPN,MANCC,MANS,NGAYNHAP,TONGTIEN) VALUES (p_mapn,p_mancc,p_mans,SYSTIMESTAMP,0);
        END IF;
    END IF;
    IF p_ngayhethan <= p_ngaysx  THEN RAISE_APPLICATION_ERROR(-20020,'LỖI: HSD phải sau NSX!'); END IF;
    IF p_ngayhethan <= SYSDATE   THEN RAISE_APPLICATION_ERROR(-20021,'LỖI: Không nhập hàng hết hạn!'); END IF;
    INSERT INTO LO_HANG(MALO,MASP,MAPN,NGAYSANXUAT,NGAYHETHAN,SOLUONGNHAP,GIANHAP)
    VALUES (p_malo,p_masp,p_mapn,p_ngaysx,p_ngayhethan,p_soluongnhap,p_gianhap) RETURNING MALO INTO p_malo;
    SELECT TONGTIEN INTO v_tongtien FROM PHIEU_NHAP WHERE MAPN = p_mapn;
    p_tongtien_out := v_tongtien;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_NHAP_KHO_LO_HANG;
/

-- SP 4: Cảnh báo hàng hết hạn
CREATE OR REPLACE PROCEDURE SP_CANH_BAO_HANG_HET_HAN (
    p_so_ngay IN NUMBER, c_result OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN c_result FOR
        SELECT l.MALO, s.MASP, s.TENSP, s.DONVITINH, l.NGAYHETHAN,
               ROUND(l.NGAYHETHAN - SYSDATE) AS SO_NGAY_CON_LAI, l.SOLUONGTON AS TON_KHO,
               CASE WHEN ROUND(l.NGAYHETHAN-SYSDATE)<=7  THEN N'Nguy hiểm'
                    WHEN ROUND(l.NGAYHETHAN-SYSDATE)<=30 THEN N'Cảnh báo'
                    ELSE N'Chú ý' END AS MUC_DO,
               ncc.TENNCC AS NHA_CUNG_CAP
        FROM   LO_HANG l
        JOIN   SAN_PHAM s  ON l.MASP  = s.MASP
        JOIN   PHIEU_NHAP pn ON l.MAPN = pn.MAPN
        JOIN   NHA_CUNG_CAP ncc ON pn.MANCC = ncc.MANCC
        WHERE  l.SOLUONGTON > 0 AND l.NGAYHETHAN > SYSDATE
          AND  (l.NGAYHETHAN - SYSDATE) <= p_so_ngay
        ORDER  BY l.NGAYHETHAN ASC;
END SP_CANH_BAO_HANG_HET_HAN;
/

-- SP 5: Thống kê doanh thu tháng
CREATE OR REPLACE PROCEDURE SP_THONG_KE_DOANH_THU_THANG (
    p_thang IN NUMBER, p_nam IN NUMBER, c_data OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN c_data FOR
        SELECT TO_CHAR(NGAYTHANHTOAN,'DD/MM/YYYY') AS NGAY,
               COUNT(MATT) AS SO_LUONG_DON, SUM(SOTIEN) AS DOANH_THU_NGAY
        FROM   THANH_TOAN
        WHERE  TRANGTHAI = N'Thành công'
          AND  EXTRACT(MONTH FROM NGAYTHANHTOAN) = p_thang
          AND  EXTRACT(YEAR  FROM NGAYTHANHTOAN) = p_nam
        GROUP  BY TO_CHAR(NGAYTHANHTOAN,'DD/MM/YYYY')
        ORDER  BY TO_CHAR(NGAYTHANHTOAN,'DD/MM/YYYY') ASC;
END SP_THONG_KE_DOANH_THU_THANG;
/

-- SP 6: Đặt lịch hẹn
CREATE OR REPLACE PROCEDURE SP_DAT_LICH_HEN (
    p_makh IN VARCHAR2, p_mans IN VARCHAR2, p_magoi IN VARCHAR2,
    p_ngayhen IN DATE, p_giohen IN TIMESTAMP, p_trieuchung IN JSON,
    p_malh_out OUT VARCHAR2
) AS
    v_ca_lam NUMBER; v_trung NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_ca_lam FROM LICH_LAM_VIEC
    WHERE  MANS = p_mans AND NGAY_LAM = TRUNC(p_ngayhen) AND IS_NGHI = 0;
    IF v_ca_lam = 0 THEN RAISE_APPLICATION_ERROR(-20035,'Bác sĩ không làm việc ngày này!'); END IF;
    SELECT COUNT(*) INTO v_trung FROM LICH_HEN
    WHERE  MANS = p_mans AND GIO_HEN = p_giohen AND TRANGTHAI != N'Đã hủy';
    IF v_trung > 0 THEN RAISE_APPLICATION_ERROR(-20036,'Slot đã được đặt!'); END IF;
    INSERT INTO LICH_HEN(MALH,MAKH,MANS,MAGOI,NGAYHEN,GIO_HEN,LOAI_LICH,TRIEU_CHUNG,TRANGTHAI)
    VALUES (NULL,p_makh,p_mans,p_magoi,p_ngayhen,p_giohen,N'Online',p_trieuchung,N'Mới')
    RETURNING MALH INTO p_malh_out;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_DAT_LICH_HEN;
/

-- SP 7: Tạo lịch làm việc bác sĩ/KTV
CREATE OR REPLACE PROCEDURE SP_TAO_LICH_LAM_VIEC (
    p_mans IN VARCHAR2, p_ngay_lam IN DATE,
    p_gio_bat_dau IN NUMBER, p_gio_ket_thuc IN NUMBER, p_is_nghi IN NUMBER DEFAULT 0
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM NHAN_SU WHERE MANS = p_mans AND IS_DELETED = 0;
    IF v_count = 0 THEN RAISE_APPLICATION_ERROR(-20080,'Nhân sự không tồn tại hoặc đã nghỉ!'); END IF;
    IF p_gio_bat_dau >= p_gio_ket_thuc THEN RAISE_APPLICATION_ERROR(-20081,'Giờ kết thúc phải > giờ bắt đầu!'); END IF;
    SELECT COUNT(*) INTO v_count FROM LICH_LAM_VIEC
    WHERE  MANS = p_mans AND NGAY_LAM = p_ngay_lam AND IS_NGHI = 0
      AND  (p_gio_bat_dau < GIO_KET_THUC AND p_gio_ket_thuc > GIO_BAT_DAU);
    IF v_count > 0 THEN RAISE_APPLICATION_ERROR(-20083,'Khung giờ bị trùng lịch!'); END IF;
    INSERT INTO LICH_LAM_VIEC(MALLV,MANS,NGAY_LAM,GIO_BAT_DAU,GIO_KET_THUC,IS_NGHI)
    VALUES (NULL,p_mans,p_ngay_lam,p_gio_bat_dau,p_gio_ket_thuc,p_is_nghi);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_TAO_LICH_LAM_VIEC;
/

-- SP 8: Cập nhật trạng thái hàng chờ
CREATE OR REPLACE PROCEDURE SP_CAP_NHAT_HANG_CHO (
    p_mahc IN VARCHAR2, p_trang_thai IN NVARCHAR2, p_gio_vao_kham IN TIMESTAMP DEFAULT NULL
) AS
    v_current_state NVARCHAR2(30);
BEGIN
    SELECT TRANG_THAI INTO v_current_state FROM HANG_CHO WHERE MAHC = p_mahc;
    IF p_trang_thai NOT IN (N'Đang khám', N'Hoàn thành', N'Bỏ về') THEN
        RAISE_APPLICATION_ERROR(-20070,'Trạng thái không hợp lệ!');
    END IF;
    IF v_current_state = N'Đang chờ' AND p_trang_thai = N'Đang khám' THEN
        UPDATE HANG_CHO SET TRANG_THAI = p_trang_thai,
            GIO_VAO_KHAM = NVL(p_gio_vao_kham, SYSTIMESTAMP) WHERE MAHC = p_mahc;
    ELSIF v_current_state = N'Đang khám' AND p_trang_thai IN (N'Hoàn thành', N'Bỏ về') THEN
        UPDATE HANG_CHO SET TRANG_THAI = p_trang_thai WHERE MAHC = p_mahc;
        UPDATE LICH_HEN SET TRANGTHAI = N'Đã khám'
        WHERE  MALH = (SELECT MALH FROM HANG_CHO WHERE MAHC = p_mahc) AND TRANGTHAI = N'Mới';
    ELSE
        RAISE_APPLICATION_ERROR(-20071,'Không thể chuyển từ [' || v_current_state || '] → [' || p_trang_thai || ']!');
    END IF;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK; RAISE_APPLICATION_ERROR(-20072,'Mã hàng chờ không tồn tại!');
    WHEN OTHERS        THEN ROLLBACK; RAISE;
END SP_CAP_NHAT_HANG_CHO;
/
-- SP 9: Giao việc cắt kính cho kỹ thuật viên
CREATE OR REPLACE PROCEDURE SP_GIAO_XU_LY_KINH (
    p_madon          IN VARCHAR2,
    p_mans_ky_thuat  IN VARCHAR2,
    p_thong_so_kinh  IN JSON,
    p_maxl_out       OUT VARCHAR2
) AS
    v_tencv  CHUC_VU.TENCV%TYPE;
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exists FROM PHIEU_KE_DON WHERE MADON = p_madon;
    IF v_exists = 0 THEN RAISE_APPLICATION_ERROR(-20090,'Phiếu kê đơn không tồn tại!'); END IF;
    SELECT cv.TENCV INTO v_tencv FROM NHAN_SU ns JOIN CHUC_VU cv ON ns.MACV = cv.MACV
    WHERE  ns.MANS = p_mans_ky_thuat AND ns.IS_DELETED = 0;
    IF v_tencv != N'Kỹ thuật viên mắt kính' THEN
        RAISE_APPLICATION_ERROR(-20091,'Chỉ KTV mắt kính mới nhận việc cắt kính!');
    END IF;
    INSERT INTO XU_LY_KINH(MAXL, MADON, THONG_SO_KINH, TRANG_THAI, NGAY_BAT_DAU, MANS_KY_THUAT)
    VALUES (NULL, p_madon, p_thong_so_kinh, N'Đang cắt', SYSTIMESTAMP, p_mans_ky_thuat)
    RETURNING MAXL INTO p_maxl_out;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_GIAO_XU_LY_KINH;
/
CREATE OR REPLACE PROCEDURE SP_TAO_HOA_DON (
    p_makh        IN VARCHAR2,
    p_mans        IN VARCHAR2,
    p_mahoso      IN VARCHAR2,
    p_madon       IN VARCHAR2,
    p_json_sp     IN CLOB, -- Dạng: '[{"malo":"L01","sl":2,"gia":150000}]'
    p_json_dv     IN CLOB, -- Dạng: '[{"madv":"DV01","sl":1,"gia":500000}]'
    p_mahd_out    OUT VARCHAR2
) AS
    v_mahd VARCHAR2(20);
BEGIN
    -- 1. Tạo vỏ Hóa Đơn (TONGTIEN ban đầu = 0, Trigger sẽ tự cộng dồn)
    INSERT INTO HOA_DON(MAHD, MAKH, MANS, MAHOSO, MADON, NGAYLAP, TONGTIEN, TRANGTHAI, IS_DELETED)
    VALUES (NULL, p_makh, p_mans, p_mahoso, p_madon, SYSTIMESTAMP, 0, N'Chưa thanh toán', 0)
    RETURNING MAHD INTO v_mahd;
    -- 2. Insert Chi tiết Sản phẩm (dùng JSON_TABLE bung chuỗi JSON)
    IF p_json_sp IS NOT NULL THEN
        INSERT INTO CT_HOA_DON (MAHD, MALO, SOLUONG, DON_GIA)
        SELECT v_mahd, j.malo, j.sl, j.gia
        FROM JSON_TABLE(p_json_sp, '$[*]'
            COLUMNS (
                malo VARCHAR2(20) PATH '$.malo',
                sl   NUMBER       PATH '$.sl',
                gia  NUMBER       PATH '$.gia'
            )
        ) j;
    END IF;
    -- 3. Insert Chi tiết Dịch vụ
    IF p_json_dv IS NOT NULL THEN
        INSERT INTO CT_HOA_DON_DV (MAHD, MADV, SOLUONG, DONGIA)
        SELECT v_mahd, j.madv, j.sl, j.gia
        FROM JSON_TABLE(p_json_dv, '$[*]'
            COLUMNS (
                madv VARCHAR2(20) PATH '$.madv',
                sl   NUMBER       PATH '$.sl',
                gia  NUMBER       PATH '$.gia'
            )
        ) j;
    END IF;

    p_mahd_out := v_mahd;
    COMMIT;
EXCEPTION 
    WHEN OTHERS THEN 
        ROLLBACK; 
        RAISE;
END SP_TAO_HOA_DON;
/
CREATE OR REPLACE PROCEDURE SP_HUY_HOA_DON (
    p_mahd IN VARCHAR2
) AS
    v_trang_thai NVARCHAR2(50);
BEGIN
    SELECT TRANGTHAI INTO v_trang_thai FROM HOA_DON WHERE MAHD = p_mahd;
    
    IF v_trang_thai = N'Đã thanh toán' THEN
        RAISE_APPLICATION_ERROR(-20095, 'LỖI: Không thể hủy hóa đơn đã thanh toán thành công!');
    ELSIF v_trang_thai = N'Đã hủy' THEN
        RAISE_APPLICATION_ERROR(-20096, 'LỖI: Hóa đơn này đã được hủy trước đó!');
    END IF;

    -- Cập nhật trạng thái. Nhờ có TRG_HOA_DON_HUY (bạn định nghĩa ở bước trước), 
    -- tồn kho của LO_HANG sẽ tự động được cộng trả lại.
    UPDATE HOA_DON SET TRANGTHAI = N'Đã hủy' WHERE MAHD = p_mahd;

    COMMIT;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        ROLLBACK; 
        RAISE_APPLICATION_ERROR(-20094, 'LỖI: Mã hóa đơn không tồn tại!');
    WHEN OTHERS THEN 
        ROLLBACK; 
        RAISE;
END SP_HUY_HOA_DON;
/
CREATE OR REPLACE PROCEDURE SP_HUY_LICH_HEN (
    p_malh IN VARCHAR2
) AS
    v_trang_thai NVARCHAR2(50);
BEGIN
    SELECT TRANGTHAI INTO v_trang_thai FROM LICH_HEN WHERE MALH = p_malh;
    
    IF v_trang_thai IN (N'Đã khám', N'Đang khám') THEN
        RAISE_APPLICATION_ERROR(-20098, 'LỖI: Lịch hẹn đang hoặc đã diễn ra, không thể hủy!');
    END IF;

    UPDATE LICH_HEN SET TRANGTHAI = N'Đã hủy' WHERE MALH = p_malh;
    
    -- Nếu KH có trong hàng chờ mà hủy lịch, đuổi khỏi hàng chờ luôn
    UPDATE HANG_CHO SET TRANG_THAI = N'Bỏ về' 
    WHERE MALH = p_malh AND TRANG_THAI = N'Đang chờ';

    COMMIT;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        ROLLBACK; 
        RAISE_APPLICATION_ERROR(-20097, 'LỖI: Mã lịch hẹn không tồn tại!');
    WHEN OTHERS THEN 
        ROLLBACK; 
        RAISE;
END SP_HUY_LICH_HEN;
/
-- CREATE OR REPLACE PROCEDURE SP_TAO_HOA_DON (
--     p_makh        IN VARCHAR2,
--     p_mans        IN VARCHAR2,
--     p_mahoso      IN VARCHAR2,
--     p_madon       IN VARCHAR2,
--     p_json_sp     IN CLOB, -- Dạng: '[{"malo":"L01","sl":2,"gia":150000}]'
--     p_json_dv     IN CLOB, -- Dạng: '[{"madv":"DV01","sl":1,"gia":500000}]'
--     p_mahd_out    OUT VARCHAR2
-- ) AS
--     v_mahd VARCHAR2(20);
-- BEGIN
--     -- 1. Tạo vỏ Hóa Đơn (TONGTIEN ban đầu = 0, Trigger sẽ tự cộng dồn)
--     INSERT INTO HOA_DON(MAHD, MAKH, MANS, MAHOSO, MADON, NGAYLAP, TONGTIEN, TRANGTHAI, IS_DELETED)
--     VALUES (NULL, p_makh, p_mans, p_mahoso, p_madon, SYSTIMESTAMP, 0, N'Chưa thanh toán', 0)
--     RETURNING MAHD INTO v_mahd;

--     -- 2. Insert Chi tiết Sản phẩm (dùng JSON_TABLE bung chuỗi JSON)
--     IF p_json_sp IS NOT NULL THEN
--         INSERT INTO CT_HOA_DON (MAHD, MALO, SOLUONG, DON_GIA)
--         SELECT v_mahd, j.malo, j.sl, j.gia
--         FROM JSON_TABLE(p_json_sp, '$[*]'
--             COLUMNS (
--                 malo VARCHAR2(20) PATH '$.malo',
--                 sl   NUMBER       PATH '$.sl',
--                 gia  NUMBER       PATH '$.gia'
--             )
--         ) j;
--     END IF;

--     -- 3. Insert Chi tiết Dịch vụ
--     IF p_json_dv IS NOT NULL THEN
--         INSERT INTO CT_HOA_DON_DV (MAHD, MADV, SOLUONG, DONGIA)
--         SELECT v_mahd, j.madv, j.sl, j.gia
--         FROM JSON_TABLE(p_json_dv, '$[*]'
--             COLUMNS (
--                 madv VARCHAR2(20) PATH '$.madv',
--                 sl   NUMBER       PATH '$.sl',
--                 gia  NUMBER       PATH '$.gia'
--             )
--         ) j;
--     END IF;

--     p_mahd_out := v_mahd;
--     COMMIT;
-- EXCEPTION 
--     WHEN OTHERS THEN 
--         ROLLBACK; 
--         RAISE;
-- END SP_TAO_HOA_DON;
-- /
-- ============================================================
-- PHẦN VI: VIEWS
-- ============================================================

-- Rating trung bình bác sĩ
CREATE OR REPLACE VIEW V_RATING_BAC_SI AS
SELECT ns.MANS, ns.HOTEN, ns.CHUYENKHOA,
       COUNT(dg.MADG) AS TONG_LUOT_DANH_GIA,
       ROUND(AVG(dg.SO_SAO),1) AS RATING_TRUNG_BINH
FROM   NHAN_SU ns
LEFT JOIN DANH_GIA dg ON ns.MANS = dg.MANS AND dg.IS_HIDDEN = 0
WHERE  ns.IS_DELETED = 0
GROUP  BY ns.MANS, ns.HOTEN, ns.CHUYENKHOA;

-- Slot trống bác sĩ
CREATE OR REPLACE VIEW V_SLOT_TRONG AS
SELECT llv.MANS, ns.HOTEN AS TEN_BAC_SI, llv.NGAY_LAM, llv.GIO_BAT_DAU, llv.GIO_KET_THUC,
       CASE WHEN EXISTS (
           SELECT 1 FROM LICH_HEN lh
           WHERE  lh.MANS = llv.MANS AND lh.GIO_HEN IS NOT NULL
             AND  TRUNC(lh.GIO_HEN) = llv.NGAY_LAM AND lh.TRANGTHAI != N'Đã hủy'
             AND  EXTRACT(HOUR FROM lh.GIO_HEN) + EXTRACT(MINUTE FROM lh.GIO_HEN)/60.0
                  BETWEEN llv.GIO_BAT_DAU AND llv.GIO_KET_THUC
       ) THEN N'Đã đặt' ELSE N'Còn trống' END AS TRANG_THAI_SLOT
FROM   LICH_LAM_VIEC llv
JOIN   NHAN_SU ns ON llv.MANS = ns.MANS
WHERE  llv.IS_NGHI = 0 AND llv.NGAY_LAM >= TRUNC(SYSDATE) AND ns.IS_DELETED = 0;

-- Hàng chờ hôm nay
CREATE OR REPLACE VIEW V_HANG_CHO_HOM_NAY AS
SELECT hc.MAHC, hc.SO_THU_TU, hc.LOAI_KHACH,
       NVL(kh.HOTEN, hc.TEN_KHACH) AS TEN_KHACH, kh.SDT,
       ns.HOTEN AS TEN_BAC_SI, gk.TENGOI AS GOI_KHAM,
       hc.TRANG_THAI, hc.GIO_DANG_KY, hc.GIO_VAO_KHAM,
       ROUND((SYSTIMESTAMP - hc.GIO_DANG_KY) * 24 * 60) AS PHUT_CHO
FROM   HANG_CHO hc
LEFT JOIN KHACH_HANG kh ON hc.MAKH = kh.MAKH
LEFT JOIN NHAN_SU    ns ON hc.MANS_PHAN_CONG = ns.MANS
LEFT JOIN LICH_HEN   lh ON hc.MALH = lh.MALH
LEFT JOIN GOI_KHAM   gk ON lh.MAGOI = gk.MAGOI
WHERE  TRUNC(hc.GIO_DANG_KY) = TRUNC(SYSDATE)
  AND  hc.TRANG_THAI NOT IN (N'Hoàn thành', N'Bỏ về')
ORDER BY CASE WHEN hc.LOAI_KHACH = N'Walk-in' THEN 0 ELSE 1 END, hc.SO_THU_TU;

-- Cảnh báo tồn kho tối thiểu
CREATE OR REPLACE VIEW V_CANH_BAO_TON_KHO AS
SELECT sp.MASP, sp.TENSP, sp.DONVITINH,
       NVL(SUM(lh.SOLUONGTON),0) AS TONG_TON,
       sp.TON_KHO_TOI_THIEU,
       CASE WHEN NVL(SUM(lh.SOLUONGTON),0) = 0                        THEN N'Het hang'
            WHEN NVL(SUM(lh.SOLUONGTON),0) <= sp.TON_KHO_TOI_THIEU     THEN N'Sap het'
            WHEN NVL(SUM(lh.SOLUONGTON),0) <= sp.TON_KHO_TOI_THIEU * 2 THEN N'Canh bao'
            ELSE N'On dinh' END AS MUC_DO
FROM   SAN_PHAM sp
LEFT JOIN LO_HANG lh ON sp.MASP = lh.MASP AND lh.NGAYHETHAN > SYSDATE AND lh.SOLUONGTON > 0
GROUP BY sp.MASP, sp.TENSP, sp.DONVITINH, sp.TON_KHO_TOI_THIEU
HAVING NVL(SUM(lh.SOLUONGTON),0) <= sp.TON_KHO_TOI_THIEU * 2 OR NVL(SUM(lh.SOLUONGTON),0) = 0;

-- ============================================================
-- PHẦN VII: INDEXES
-- ============================================================
CREATE INDEX IDX_CTHD_MAHD    ON CT_HOA_DON (MAHD);
CREATE INDEX IDX_CTHD_MALO    ON CT_HOA_DON (MALO);
CREATE INDEX IDX_LO_MASP      ON LO_HANG (MASP);
CREATE INDEX IDX_LO_MAPN      ON LO_HANG (MAPN);
CREATE INDEX IDX_LO_HSD       ON LO_HANG (NGAYHETHAN);
CREATE INDEX IDX_LO_TON       ON LO_HANG (SOLUONGTON);
CREATE INDEX IDX_HD_MAKH      ON HOA_DON (MAKH);
CREATE INDEX IDX_HD_MANS      ON HOA_DON (MANS);
CREATE INDEX IDX_HD_TRANG     ON HOA_DON (TRANGTHAI);
CREATE INDEX IDX_HD_NGAY      ON HOA_DON (NGAYLAP);
CREATE INDEX IDX_HD_DEL       ON HOA_DON (IS_DELETED);
CREATE INDEX IDX_KH_DEL       ON KHACH_HANG (IS_DELETED);
CREATE INDEX IDX_NS_DEL       ON NHAN_SU (IS_DELETED);
CREATE INDEX IDX_TT_MAHD      ON THANH_TOAN (MAHD);
CREATE INDEX IDX_TT_NGAY      ON THANH_TOAN (NGAYTHANHTOAN);
CREATE INDEX IDX_TT_TRANG     ON THANH_TOAN (TRANGTHAI);
CREATE INDEX IDX_TT_THONGKE   ON THANH_TOAN (TRANGTHAI, NGAYTHANHTOAN, SOTIEN);
CREATE INDEX IDX_HS_MAKH      ON HO_SO_THI_LUC (MAKH);
CREATE INDEX IDX_HS_MANS      ON HO_SO_THI_LUC (MANS);
CREATE INDEX IDX_HS_NGAY      ON HO_SO_THI_LUC (NGAYKHAM);
CREATE INDEX IDX_LH_MAKH      ON LICH_HEN (MAKH);
CREATE INDEX IDX_LH_TRANG     ON LICH_HEN (TRANGTHAI);
CREATE INDEX IDX_LH_NGAY      ON LICH_HEN (NGAYHEN);
CREATE INDEX IDX_LH_GIO       ON LICH_HEN (GIO_HEN);
CREATE INDEX IDX_CTKD_MADON   ON CT_KE_DON (MADON);
CREATE INDEX IDX_CTKD_MASP    ON CT_KE_DON (MASP);
CREATE INDEX IDX_PN_MANCC     ON PHIEU_NHAP (MANCC);
CREATE INDEX IDX_PN_MANS      ON PHIEU_NHAP (MANS);
CREATE INDEX IDX_PX_MAHD      ON PHIEU_XUAT (MAHD);
CREATE INDEX IDX_NS_MACV      ON NHAN_SU (MACV);
CREATE INDEX IDX_NS_MATK      ON NHAN_SU (MATK);
CREATE INDEX IDX_LLV_MANS     ON LICH_LAM_VIEC (MANS);
CREATE INDEX IDX_LLV_NGAY     ON LICH_LAM_VIEC (NGAY_LAM);
CREATE INDEX IDX_DG_MANS      ON DANH_GIA (MANS);
CREATE INDEX IDX_HC_NGAY      ON HANG_CHO (GIO_DANG_KY);
CREATE INDEX IDX_HC_TRANG     ON HANG_CHO (TRANG_THAI);
CREATE INDEX IDX_XLK_MANS     ON XU_LY_KINH (MANS_KY_THUAT);
CREATE INDEX IDX_XLK_TRANG    ON XU_LY_KINH (TRANG_THAI);
CREATE INDEX IDX_GDNCC_MANCC  ON GIAO_DICH_NCC (MANCC);

-- ============================================================
COMMIT;

