-- Bảng Lịch sử điểm thưởng
CREATE TABLE LICH_SU_DIEM (
    MALSD     VARCHAR2(10)  PRIMARY KEY,
    MAKH      VARCHAR2(10)  NOT NULL,
    LOAI      NVARCHAR2(20) NOT NULL,   -- Cong | Tru | Quy_doi | Hoan
    SO_DIEM   NUMBER        NOT NULL,
    LY_DO     NVARCHAR2(200),
    MAHD      VARCHAR2(10)  NULL,
    THOI_GIAN TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LSD_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_LSD_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD),
    CONSTRAINT CK_LSD_LOAI CHECK (LOAI IN (N'Cong', N'Tru', N'Quy_doi', N'Hoan'))
);
-- Lịch sử thay đổi giá sản phẩm
CREATE TABLE LICH_SU_GIA (
    MALSG          VARCHAR2(10)  PRIMARY KEY,
    MASP           VARCHAR2(10)  NOT NULL,
    GIA_CU         NUMBER(15,2)  NOT NULL,
    GIA_MOI        NUMBER(15,2)  NOT NULL,
    NGAY_AP_DUNG   TIMESTAMP     DEFAULT SYSTIMESTAMP,
    NGUOI_CAP_NHAT VARCHAR2(50),
    LY_DO          NVARCHAR2(200),
    CONSTRAINT FK_LSG_SP FOREIGN KEY (MASP) REFERENCES SAN_PHAM(MASP)
);
CREATE SEQUENCE SEQ_LICH_SU_GIA START WITH 1 INCREMENT BY 1 CACHE 10 NOCYCLE;
CREATE OR REPLACE TRIGGER TRG_GEN_MALSG
BEFORE INSERT ON LICH_SU_GIA FOR EACH ROW
BEGIN IF :NEW.MALSG IS NULL THEN :NEW.MALSG := 'LG' || LPAD(SEQ_LICH_SU_GIA.NEXTVAL,6,'0'); END IF; END;
/

-- 14. Lịch sử giá — tự ghi khi giá sản phẩm thay đổi
CREATE OR REPLACE TRIGGER TRG_LICH_SU_GIA
AFTER UPDATE OF GIABAN ON SAN_PHAM
FOR EACH ROW
WHEN (OLD.GIABAN != NEW.GIABAN)
BEGIN
    INSERT INTO LICH_SU_GIA(MALSG, MASP, GIA_CU, GIA_MOI, NGAY_AP_DUNG, NGUOI_CAP_NHAT)
    VALUES (NULL, :NEW.MASP, :OLD.GIABAN, :NEW.GIABAN, SYSTIMESTAMP, USER);
END;
/
CREATE SEQUENCE SEQ_LICH_SU_DIEM START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_GEN_MALSD
BEFORE INSERT ON LICH_SU_DIEM
FOR EACH ROW
BEGIN
    IF :NEW.MALSD IS NULL THEN
        :NEW.MALSD := 'LS' || LPAD(SEQ_LICH_SU_DIEM.NEXTVAL, 6, '0');
    END IF;
END;
/

-- Bảng Khách hàng sử dụng khuyến mãi
CREATE TABLE KH_KHUYEN_MAI (
    MAKH    VARCHAR2(10),
    MAKM    VARCHAR2(10),
    MAHD    VARCHAR2(10)  NULL,
    NGAY_SD TIMESTAMP     DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_KH_KM   PRIMARY KEY (MAKH, MAKM),
    CONSTRAINT FK_KHKM_KH FOREIGN KEY (MAKH) REFERENCES KHACH_HANG(MAKH),
    CONSTRAINT FK_KHKM_KM FOREIGN KEY (MAKM) REFERENCES KHUYEN_MAI(MAKM),
    CONSTRAINT FK_KHKM_HD FOREIGN KEY (MAHD) REFERENCES HOA_DON(MAHD)
);
CREATE OR REPLACE TRIGGER TRG_AUTO_XU_LY_KINH
AFTER INSERT ON CT_KE_DON
FOR EACH ROW
DECLARE
    v_lathuoc NUMBER;
BEGIN
    SELECT LATHUOC INTO v_lathuoc FROM SAN_PHAM WHERE MASP = :NEW.MASP;
    IF v_lathuoc = 0 THEN
        INSERT INTO XU_LY_KINH(MAXL, MADON, THONG_SO_KINH, TRANG_THAI)
        VALUES (NULL, :NEW.MADON, NULL, N'Chờ xử lý');
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_AUTO_GD_NCC
AFTER INSERT ON PHIEU_NHAP
FOR EACH ROW
BEGIN
    INSERT INTO GIAO_DICH_NCC(MAGD, MANCC, LOAI, SO_TIEN, MAPN, GHI_CHU)
    VALUES (NULL, :NEW.MANCC, N'Nhập hàng', :NEW.TONGTIEN, :NEW.MAPN, N'Nhập hàng từ phiếu ' || :NEW.MAPN);
END;
/
-- Thêm ràng buộc cho bảng SAN_PHAM
ALTER TABLE SAN_PHAM ADD CONSTRAINT CK_SP_GIABAN CHECK (GIABAN >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CK_SP_TON_KHO_TOI_THIEU CHECK (TON_KHO_TOI_THIEU >= 0);

-- Thêm ràng buộc cho bảng LO_HANG
ALTER TABLE LO_HANG ADD CONSTRAINT CK_LO_NGAY CHECK (NGAYHETHAN > NGAYSANXUAT);
ALTER TABLE LO_HANG ADD CONSTRAINT CK_LO_SOLUONGNHAP CHECK (SOLUONGNHAP > 0);
ALTER TABLE LO_HANG ADD CONSTRAINT CK_LO_SOLUONGTON CHECK (SOLUONGTON >= 0);
ALTER TABLE LO_HANG ADD CONSTRAINT CK_LO_GIANHAP CHECK (GIANHAP >= 0);

-- Thêm ràng buộc cho bảng CT_KE_DON
ALTER TABLE CT_KE_DON ADD CONSTRAINT CK_CTKD_SOLUONG CHECK (SOLUONG > 0);

-- Thêm ràng buộc cho bảng CT_HOA_DON
ALTER TABLE CT_HOA_DON ADD CONSTRAINT CK_CTHD_SOLUONG CHECK (SOLUONG > 0);
ALTER TABLE CT_HOA_DON ADD CONSTRAINT CK_CTHD_DONGIA CHECK (DONGIA >= 0);

-- Thêm ràng buộc cho bảng CT_HOA_DON_DV
ALTER TABLE CT_HOA_DON_DV ADD CONSTRAINT CK_CTHD_DV_SOLUONG CHECK (SOLUONG > 0);
ALTER TABLE CT_HOA_DON_DV ADD CONSTRAINT CK_CTHD_DV_DONGIA CHECK (DONGIA >= 0);

-- Thêm ràng buộc cho bảng THANH_TOAN
ALTER TABLE THANH_TOAN ADD CONSTRAINT CK_TT_SOTIEN CHECK (SOTIEN > 0);

-- Thêm ràng buộc cho bảng PHIEU_NHAP
ALTER TABLE PHIEU_NHAP ADD CONSTRAINT CK_PN_TONGTIEN CHECK (TONGTIEN >= 0);
ALTER TABLE LICH_HEN ADD CONSTRAINT CK_LH_TRANGTHAI CHECK (TRANGTHAI IN (N'Mới', N'Đã khám', N'Đã hủy'));
ALTER TABLE LICH_HEN ADD CONSTRAINT CK_LH_LOAI_LICH CHECK (LOAI_LICH IN (N'Online', N'Walk-in'));

-- SP cộng điểm thủ công
CREATE OR REPLACE PROCEDURE SP_CONG_DIEM (
    p_makh    IN VARCHAR2,
    p_so_diem IN NUMBER,
    p_ly_do   IN NVARCHAR2,
    p_mahd    IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    UPDATE KHACH_HANG SET DIEMTICHLUY = DIEMTICHLUY + p_so_diem WHERE MAKH = p_makh;
    INSERT INTO LICH_SU_DIEM (MALSD, MAKH, LOAI, SO_DIEM, LY_DO, MAHD)
    VALUES (NULL, p_makh, N'Cong', p_so_diem, p_ly_do, p_mahd);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_CONG_DIEM;
/

-- SP đổi điểm lấy voucher (có thể tạo voucher mới hoặc lấy từ bảng KHUYEN_MAI)
CREATE OR REPLACE PROCEDURE SP_DOI_DIEM_LAY_VOUCHER (
    p_makh       IN VARCHAR2,
    p_diem_doi   IN NUMBER,
    p_makm_out   OUT VARCHAR2
) AS
    v_diem_hien_tai NUMBER;
    v_ma_km VARCHAR2(10);
BEGIN
    SELECT DIEMTICHLUY INTO v_diem_hien_tai FROM KHACH_HANG WHERE MAKH = p_makh;
    IF v_diem_hien_tai < p_diem_doi THEN
        RAISE_APPLICATION_ERROR(-20092, 'Không đủ điểm để đổi!');
    END IF;
    -- Tìm khuyến mãi có loại DoiDiem và giá trị điểm tương ứng
    SELECT MAKM INTO v_ma_km
    FROM KHUYEN_MAI
    WHERE LOAI = N'DoiDiem' AND GIA_TRI <= p_diem_doi AND IS_ACTIVE = 1
      AND NGAY_BD <= SYSDATE AND NGAY_KT >= SYSDATE
      AND (SO_LUONG IS NULL OR DA_DUNG < SO_LUONG)
      AND ROWNUM = 1;
    IF v_ma_km IS NULL THEN
        RAISE_APPLICATION_ERROR(-20093, 'Không có khuyến mãi phù hợp!');
    END IF;
    -- Trừ điểm
    UPDATE KHACH_HANG SET DIEMTICHLUY = DIEMTICHLUY - p_diem_doi WHERE MAKH = p_makh;
    INSERT INTO LICH_SU_DIEM (MALSD, MAKH, LOAI, SO_DIEM, LY_DO)
    VALUES (NULL, p_makh, N'Tru', p_diem_doi, N'Đổi điểm lấy voucher');
    -- Ghi nhận voucher vào bảng KH_KHUYEN_MAI (sẽ được áp dụng sau)
    INSERT INTO KH_KHUYEN_MAI (MAKH, MAKM) VALUES (p_makh, v_ma_km);
    p_makm_out := v_ma_km;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END SP_DOI_DIEM_LAY_VOUCHER;
/
ALTER TABLE THANH_TOAN ADD CONSTRAINT CK_TT_TRANGTHAI CHECK (TRANGTHAI IN (N'Thành công', N'Thất bại'));
CREATE INDEX IDX_LSD_MAKH ON LICH_SU_DIEM (MAKH);
CREATE INDEX IDX_LSD_MAHD ON LICH_SU_DIEM (MAHD);