version: "3.9"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../.devcontainer/backend/Dockerfile
    container_name: spring_backend
    command: sleep infinity
    volumes:
      - ..:/workspaces/da:cached
      - maven_cache:/root/.m2
    ports:
      - "8080:8080"

volumes:
  maven_cache: